spring.application.name=backend
spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:47418/railway
spring.datasource.username=root
spring.datasource.password=FQycLJdppcISgMKGYYTwgrKqifFEGgIp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8081}
spring.jpa.open-in-view=true
